"""updated user schema password token nullable to true

Revision ID: bdf301b5d0db
Revises: e44fd1ebf518
Create Date: 2025-12-27 20:04:39.511648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf301b5d0db'
down_revision: Union[str, Sequence[str], None] = 'e44fd1ebf518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passwordToken',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passwordToken',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
